#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_OPTIONS                             105
#define IDD_OPTIONS_LEGACY                      106
#define IDD_ONSTOP                              107
#define IDD_ONSTOP_LEGACY                       108
#define IDD_RESERVATION                         112
#define IDD_RESERVATION_LEGACY                  113
#define IDD_QUERY                               114
#define IDD_QUERY_LEGACY                        115
#define IDC_STATIC_ONSTOP                       1000
#define IDC_DELETE                              1001
#define IDC_STATIC_TOT                          1001
#define IDC_CHECK_EVENT_NAME                    1002
#define IDC_CHECK_JOIN_EVENTS                   1002
#define IDC_PROGRESS_ONSTOP                     1002
#define IDC_STATIC_RES_TIME                     1002
#define IDC_COMBO_DRIVER_NAME                   1003
#define IDC_COMBO_NIBBLE1                       1003
#define IDC_CHECK_RES_TIME                      1003
#define IDC_COMBO_TOT                           1004
#define IDC_EDIT_EVENT_NUM                      1004
#define IDC_CHECK_SET_PREVIEW                   1005
#define IDC_EDIT_EVENT_NAME                     1005
#define IDC_EDIT_CH_CHANGE                      1006
#define IDC_STATIC_SERVICE_NAME                 1006
#define IDC_CHECK_CASE                          1007
#define IDC_EDIT_SPIN_UP                        1007
#define IDC_STATIC_EVENT_NAME                   1007
#define IDC_COMBO_NOTIFY_LEVEL                  1008
#define IDC_COMBO_LOG_LEVEL                     1009
#define IDC_CHECK_EVENT_RELAY                   1010
#define IDC_EDIT_OPTION                         1016
#define IDC_EDIT_RSM_M                          1017
#define IDC_CHECK_USE_TASK                      1018
#define IDC_CHECK_SET_PREVIEW_NO_VIEW_ONLY      1019
#define IDC_CHECK_NOWAKE_VIEW_ONLY              1020
#define IDC_CHECK_SHOW_DLG_SUS                  1021
#define IDC_CHECK_ALWAYS_DRAW_PROGRAM_RECT      1022
#define IDC_COMBO_SUB_DRIVER_NAME               1023
#define IDC_STATIC_STA_HOUR                     1030
#define IDC_STATIC_STA_MIN                      1031
#define IDC_STATIC_STA_SEC                      1032
#define IDC_STATIC_DUR_MIN                      1033
#define IDC_STATIC_DUR_SEC                      1034
#define IDC_EDIT_STA_HOUR                       1035
#define IDC_EDIT_STA_MIN                        1036
#define IDC_EDIT_STA_SEC                        1037
#define IDC_EDIT_DUR_MIN                        1038
#define IDC_EDIT_DUR_SEC                        1039
#define IDC_EDIT_KEYWORD                        1042
#define IDC_COMBO_DUR_HOUR                      1067
#define IDC_COMBO_DUR_MIN                       1068
#define IDC_COMBO_STA_MIN                       1069
#define IDC_COMBO_STA_HOUR                      1070
#define IDC_COMBO_NIBBLE2                       1071
#define IDC_CHECK_SUN                           1072
#define IDC_CHECK_MON                           1073
#define IDC_CHECK_TUE                           1074
#define IDC_CHECK_WED                           1075
#define IDC_CHECK_THU                           1076
#define IDC_CHECK_FRI                           1077
#define IDC_CHECK_SAT                           1078
#define IDC_DISABLE                             1084
#define IDC_CHECK_VIEW_ONLY                     2000
#define IDC_CHECK_STA_M                         2001
#define IDC_CHECK_END_M                         2002
#define IDC_CHECK_SAVE_DIR                      2003
#define IDC_CHECK_SAVE_NAME                     2004
#define IDC_EDIT_STA_M                          2005
#define IDC_EDIT_END_M                          2006
#define IDC_EDIT_SAVE_DIR                       2007
#define IDC_EDIT_SAVE_NAME                      2008
#define IDC_COMBO_PRI                           2009
#define IDC_COMBO_ONSTOP                        2010
#define IDC_BUTTON_SAVE_DIR_BROWSE              2011
#define IDC_EDIT_STA_TRIM                       2012
#define IDC_EDIT_END_TRIM                       2013
